name: "bge-m3"
backend: "python"

input [
  {
    name: "text_snippet"
    data_type: TYPE_STRING
    dims: [-1]
  }
]

output [
  {
    name: "embedding"
    data_type: TYPE_FP32
    dims: [ -1, 1024 ]
  }
]

instance_group [
  {
    count: 0
    kind: KIND_GPU
  }
]
