name: "e5"
backend: "python"

input [
  {
    name: "instruction"
    data_type: TYPE_STRING
    dims: [1]
  },
  {
    name: "text_snippet"
    data_type: TYPE_STRING
    dims: [1]
  }
]

output [
  {
    name: "embedding"
    data_type: TYPE_FP32
    dims: [1024]
  }
]

instance_group [
  {
    count: 5
    kind: KIND_GPU
  }
]
